In [1]:
import numpy as np

In [5]:
A = np.array([[2, 6, 5, 2],
              [2, -2, 2, 3],
              [1, 5, 4, 0]])

B = np.array([[2, 9, 0, 3, 0],
              [3, 6, 8, -2, 2],
              [1, 3, 5, 0, 1],
              [3, 0, 2, 0, 5]])
print(A.shape)
print(B.shape)

print("Matmul C =: \n")
print(np.matmul(A, B), "\n")

print("Einsum C =: \n")
print(np.einsum('ij,jk -> ik', A, B))

(3, 4)
(4, 5)
Matmul C =: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]] 

Einsum C =: 

[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [10]:
A = np.array([[2, 6, 5, 2],
              [2, -2, 2, 3],
              [1, 5, 4, 0]])

B = np.array([[2, 9, 0, 3],
              [3, 6, 8, -2],
              [1, 3, 5, 0]])
print(A.shape, B.shape)


print("Hardamond C =: \n")
print(A*B, "\n")

print("Einsum C=: \n")
print(np.einsum('ij,ij -> ij', A, B))

(3, 4) (3, 4)
Hardamond C =: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

Einsum C=: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [16]:
A = np.array([[2, 6, 5, 2],
              [2, -2, 2, 3],
              [1, 5, 4, 0]])

print("Transposed A =: \n")
print(A.T, "\n")

print("Einsum Transpose A =: \n")
print(np.einsum("ij -> ji", A))

Transposed A =: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]] 

Einsum Transpose A =: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [20]:
A = np.array([
               [[2, 6, 5, 2],
                [2, -2, 2, 3],
                [1, 5, 4, 0]],

               [[1, 3, 1, 22],
                [0, 2, 2, 0],
                [1, 5, 4, 1]] ])

B = np.array([
               [[2, 9, 0, 3, 0],
                [3, 6, 8, -2, 2],
                [1, 3, 5, 0, 1],
                [3, 0, 2, 0, 5]],

               [[1, 0, 0, 3, 0],
                [3, 0, 4, -2, 2],
                [1, 0, 2, 0, 0],
                [3, 0, 1, 1, 0]] ])


print(A.shape, B.shape)

print("Batch Multiplication C =: \n")
print(np.matmul(A,B), "\n")

print("Einsum C =: \n")
print(np.einsum('bij,bjk -> bik', A,B))

(2, 3, 4) (2, 4, 5)
Batch Multiplication C =: 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 

Einsum C =: 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [23]:
A = np.array([
               [[2, 6, 5, 2],
                [2, -2, 2, 3],
                [1, 5, 4, 0]],

               [[1, 3, 1, 22],
                [0, 2, 2, 0],
                [1, 5, 4, 1]] ])

print("Sum A =: \n")
print(np.sum(A), "\n")

print("Einsum A =: \n")
print(np.einsum('bij -> ', A))

Sum A =: 

72 

Einsum A =: 

72


In [25]:
A = np.array([[2, 6, 5, 2],
              [2, -2, 2, 3],
              [1, 5, 4, 0]])

# print("Axis 0 Sum A =: \n")
# print(np.sum(A, axis = 0), "\n")

print("Einsum A =: \n")
print(np.einsum('ij -> i', A))
print("-----------------------------")

# print("Axis 1 Sum A =: \n")
# print(np.sum(A, axis = 1), "\n")

# print("Einsum A =: \n")
# print(np.einsum('ij -> i', A))



Einsum A =: 

[15  5 10]
-----------------------------


In [27]:
Q = batchsize, s_q, modelsize
K = batchsize, s_k, modelsize

In [28]:
Q = np.random.randn(32, 64, 512)
K = np.random.randn(32, 128, 512)

In [30]:
np.einsum("bqm,bkm -> bqk", Q, K).shape

(32, 64, 128)

In [39]:
A = np.random.randn(2, 4, 4, 2)
B = np.random.randn(2, 4, 4, 1)

In [40]:
np.einsum("bcik,bcij -> bckj", B, A)

array([[[[ 0.1387639 , -0.39260661]],

        [[-6.4138574 , -1.46033795]],

        [[-1.21298404,  3.15070551]],

        [[-1.67339995, -5.22771366]]],


       [[[-2.69401486,  0.7609918 ]],

        [[ 1.19256107,  2.07165269]],

        [[-2.19755847,  1.34832215]],

        [[ 2.41901056,  2.06039828]]]])

In [41]:
np.matmul(np.transpose(B, (0,1,3,2)), A)

array([[[[ 0.1387639 , -0.39260661]],

        [[-6.4138574 , -1.46033795]],

        [[-1.21298404,  3.15070551]],

        [[-1.67339995, -5.22771366]]],


       [[[-2.69401486,  0.7609918 ]],

        [[ 1.19256107,  2.07165269]],

        [[-2.19755847,  1.34832215]],

        [[ 2.41901056,  2.06039828]]]])