In [9]:
import tensorflow as tf

In [11]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [29]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [31]:
tensor_string = tf.constant(["hello world","hi "])
print(tensor_string)

tf.Tensor([b'hello world' b'hi '], shape=(2,), dtype=string)


In [28]:
tensor_one_d = tf.constant([2,0.,-3,8,90.],dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [15]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [17]:
tensor_three_d = tf.constant([
 [[1,2,0],
 [3,5,-1]],

 [[10,2,0],
 [1,0,2]],

 [[5,8,0],
 [2,7,0]],

 [[2,1,9],
 [4,-3,32]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [22]:
print(tensor_three_d.ndim)

3


In [32]:
import numpy as np

In [33]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [34]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
-Tensors are Multi Dimensional Arrays